---
title: "My First Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: flexdashboard
params:
  geonames_account: "rstudio_dashboard"
  my_city: "Boston"
  my_airport: "KBOS"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(geonames)
library(dplyr)
library(magrittr)
library(flexdashboard)
library(leaflet)

options(geonamesUsername=params$geonames_account)

gauge_minimum_temp <- -20
gauge_maximum_temp <- 40
gauge_cold_temp <- 5
gauge_hot_temp <- 25

gauge_colors = c(success = "#84dd63", warning = "#51F7F2", danger = "#ef6461")

get_weather <- function(airport_code, location) {
  wx <- GNweatherIcao(airport_code) %>% 
    select(datetime, temperature, lat, lng) %>% 
     mutate(stationName = location,
            lat = round(as.numeric(as.character(lat)), 3),
            lng = round(as.numeric(as.character(lng)), 3),
            temperature = round(as.numeric(as.character(temperature))),
            color = ifelse(temperature >= gauge_hot_temp, "#ef6461", ifelse(temperature > gauge_cold_temp, "#84dd63", "#51F7F2")))
  return(wx)
}

my_weather        <- get_weather(params$my_airport, params$my_city)
sydney_weather    <- get_weather("YSSY", "Sydney")
london_weather    <- get_weather("EGLC", "London")
mumbai_weather    <- get_weather("VABB", "Mumbai")
tdf_weather       <- get_weather("SAWH", "Tierra Del Fuego")

weather <- rbind(my_weather, sydney_weather, london_weather, mumbai_weather, tdf_weather)

latest_earthquakes <- GNearthquakes(north=90,south=-90,west=-180,east=180,date=Sys.Date(), maxRows = 50)
latest_earthquakes <- latest_earthquakes %>% 
    mutate(magnitude = round(as.numeric(as.character(magnitude)),1),
         lat = round(as.numeric(as.character(lat)), 3),
         lng = round(as.numeric(as.character(lng)), 3))


```

# Temperatures

## Gauges

### `r params$my_city`

```{r my_gauge, echo=FALSE}
gauge(my_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), 
                             danger = c(gauge_hot_temp,gauge_maximum_temp),
      colors = gauge_colors))
```

### Tierra Del Fuego

```{r cc_gauges, echo=FALSE}

gauge(tdf_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
      colors = gauge_colors))
```


### London

```{r lon_gauges, echo=FALSE}
gauge(london_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
       colors = gauge_colors))
```

### Mumbai

```{r bom_gauges, echo=FALSE}

gauge(mumbai_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
       colors = gauge_colors))
```

### Sydney

```{r anc_gauges, echo=FALSE}
gauge(sydney_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
      colors = gauge_colors))
```

## Map Section

### Description {data-width=200}
This dashboard shows you weather and recent earthquakes around the world in real-time.

The temperatures above are simple *gauge* HTML widgets. The map is generated by the *leaflet* mapping widget.

### Map
```{r temp_map, echo=FALSE}

leaflet(width = 500, height = 500) %>% 
  addTiles()  %>% 
  setView(40, 15, zoom = 2) %>% 
  addCircleMarkers(data = weather, 
            group = "Weather Stations", stroke = TRUE, fill = FALSE, 
            color = ~ color, radius = 6, opacity = 0.75,
            popup = ~ paste0(datetime, " UTC<br \\>", 
                             stationName, " Temperature<br \\>", 
                             temperature, "°C")) %>% 
  addCircleMarkers(data = latest_earthquakes,
            radius = ~ magnitude*2, stroke = FALSE, 
            fillColor = "#80532F", fillOpacity = 0.5,
            group = "Earthquakes", 
            popup = ~ paste0(datetime, " UTC<br \\>Earthquake Magnitude ", magnitude)) %>% 
  addLayersControl(
    overlayGroups = c("Weather Stations", "Earthquakes"),
    options = layersControlOptions(collapsed = FALSE))


```


  

