---
title: "Iris Data with Shiny Inputs"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(ggplot2)
theme_set(theme_minimal())
```

## Column {data-width=350}

### Inputs

```{r}
    selectInput('xcol', 'X Variable', names(iris))
    selectInput('ycol', 'Y Variable', names(iris),
                selected=names(iris)[[2]])
    numericInput('clusters', 'Cluster count', 3,
                 min = 1, max = 9)
   selectedData <- reactive({
    iris[, c(input$xcol, input$ycol)]
   })

   clusters <- reactive({
    kmeans(selectedData(), input$clusters)
   })

```

## Column {data-width=550}

### Output

```{r}

renderPlot({
    palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
      "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

    par(mar = c(5.1, 4.1, 0, 1))
    plot(selectedData(),
         col = clusters()$cluster,
         pch = 20, cex = 3)
    points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
  })

```
