---
title: "My First Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(jsonlite)
library(geonames)
library(dplyr)
library(magrittr)
library(flexdashboard)
library(leaflet)

options(geonamesUsername="rstudio_dashboard")

get_weather <- function(airport_code, location) {
  wx <- GNweatherIcao(airport_code) %>% 
    select(temperature, lat, lng) %>% 
     mutate(stationName = location,
            lat = round(as.numeric(as.character(lat)), 3),
            lng = round(as.numeric(as.character(lng)), 3),
            temperature = round(as.numeric(as.character(temperature))))
  return(wx)
}

bos_weather       <- get_weather("KBOS", "Boston")
anchorage_weather <- get_weather("PANC", "Anchorage")
london_weather    <- get_weather("EGLC", "London")
mumbai_weather    <- get_weather("VABB", "Mumbai")
tdf_weather       <- get_weather("SAWH", "Tierra Del Fuego")

weather <- rbind(bos_weather, anchorage_weather, london_weather, mumbai_weather, tdf_weather)

gauge_minimum_temp <- -20
gauge_maximum_temp <- 40
gauge_cold_temp <- 5
gauge_hot_temp <- 25

latest_earthquakes <- GNearthquakes(north=90,south=-90,west=-180,east=180,date=Sys.Date(), maxRows = 25)
latest_earthquakes <- latest_earthquakes %>% 
    mutate(magnitude = round(as.numeric(as.character(magnitude)),1),
         lat = round(as.numeric(as.character(lat)), 3),
         lng = round(as.numeric(as.character(lng)), 3))


```

# Temps

## Gauges

### Boston

```{r bos_gauge, echo=FALSE}
gauge(bos_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
      colors = c(success = "green", warning = "blue", danger = "red")))
```

### Anchorage

```{r anc_gauges, echo=FALSE}
gauge(anchorage_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
      colors = c(success = "green", warning = "blue", danger = "red")))
```

### London

```{r lon_gauges, echo=FALSE}
gauge(london_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
      colors = c(success = "green", warning = "blue", danger = "red")))
```

### Mumbai

```{r bom_gauges, echo=FALSE}

gauge(mumbai_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
      colors = c(success = "green", warning = "blue", danger = "red")))
```

### Tierra Del Fuego

```{r cc_gauges, echo=FALSE}

gauge(tdf_weather$temperature, min = gauge_minimum_temp, max = gauge_maximum_temp, symbol = "°",
      sectors = gaugeSectors(warning = c(gauge_minimum_temp, gauge_cold_temp), 
                             success = c(gauge_cold_temp,gauge_hot_temp), danger = c(gauge_hot_temp,gauge_maximum_temp),
      colors = c(success = "green", warning = "blue", danger = "red")))
```

## Map Section

### Description {data-width=200}
This dashboard shows you weather and recent earthquakes around the world in real-time.

The temperatures above are simple *gauge* HTML widgets. The map is generated by the *leaflet* mapping widget.

### Map
```{r temp_map, echo=FALSE}

leaflet(width = 500, height = 500) %>% 
  addTiles()  %>% 
  setView(0, 51.5, zoom = 2) %>% 
  addPopups(data = weather,
            group = "Weather Stations", 
            popup = ~ paste0(stationName, "<br \\>", round(as.numeric(as.character(temperature))), "°C")) %>% 
  addCircleMarkers(data = latest_earthquakes,
             radius = ~ magnitude*2, stroke = FALSE, fillColor = "#F00",
            group = "Earthquakes", 
            popup = ~ paste0(datetime, "<br \\>Magnitude ", magnitude)) %>% 
  addLayersControl(
    overlayGroups = c("Weather Stations", "Earthquakes"),
    options = layersControlOptions(collapsed = FALSE))


```

# Earthquake Map

```{r earthquake_map, echo=FALSE}

leaflet() %>% 
  addTiles()  %>% 
  setView(0, 20, zoom = 2) %>% 
  addCircleMarkers(data = latest_earthquakes,
             radius = ~ magnitude*2, stroke = FALSE, fillColor = "#F00",
            group = "Earthquakes", 
            popup = ~ paste0(datetime, "<br \\>Magnitude ", magnitude))

```

# US Weather Map

```{r weather_map}
leaflet() %>% addTiles() %>% setView(-93.65, 42.0285, zoom = 4) %>%
  addWMSTiles(
    "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi",
    layers = "nexrad-n0r-900913",
    options = WMSTileOptions(format = "image/png", transparent = TRUE),
    attribution = "Weather data © 2012 IEM Nexrad"
  )
```

  

