---
title: "Quote Poems"
author: "Frank Dobie"
---

Below is one of my favorite poems, "Silentium!" by [Fyodor Tyutchev](https://en.wikipedia.org/wiki/Fyodor_Tyutchev):

Speak not, lie hidden, and conceal
the way you dream, the things you feel.
Deep in your spirit let them rise
akin to stars in crystal skies
that set before the night is blurred:
delight in them and speak no word.

How can a heart expression find?
How should another know your mind?
Will he discern what quickens you?
A thought, once uttered, is untrue.
Dimmed is the fountainhead when stirred:
drink at the source and speak no word.

Live in your inner self alone
within your soul a world has grown,
the magic of veiled thoughts that might
be blinded by the outer light,
drowned in the noise of day, unheard...
take in their song and speak no word.

丘特切夫《别声张》

别声张，要好好地收起
自己的感情，自己的向往；
任凭它们在心灵深处
默默地升起，悄悄地沉落，
像繁星，在夜空中
任你观赏，可别声张！

心灵，该怎样表白自己？
他人又怎样理解你的思想？
各人有自己的生活体验，
一旦说出，就会变样；
发掘，只会打乱泉水的宁静
悄悄地吸吮吧，可别声张。

世界，就在你的心中
生活，要学会内向
外来的噪音
会破坏神奇和迷人的思想，
日光也会把灵感驱散。
自然的歌要潜心倾听，可别声张！
